version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: mako
      POSTGRES_USER: kline
      POSTGRES_PASSWORD: kline
    ports:
    - "5432"
    volumes:
    - ./postgresql:/var/lib/postgresql
  api:
    build:
      context: ./api
    volumes:
    - ./api:/usr/src/app
    depends_on:
    - db
    environment:
    - DATABASE_URL=postgres://kline:kline@db:5432/mako
  frontend:
    build:
      context: ./web
      args:
        UID: ${UID:-1002}
    volumes:
    - ./web:/usr/src/app
    user: frontend
  web:
    image: nginx:latest
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 3000:80
    depends_on:
      - frontend
      - api
    expose:
    - 3000